Kaonasi-biwa/builtin/pwd
kotonone/kotonemu pull request #1
Opened 2024-03-31 06:36 UTC by kaonasi-biwa

pwdコマンドです  
-Pは一旦後回しですが、それ以外は基本的にUbuntu(WSLの20.04.6 LSTで確認)と同じ動作をしていると思います

2024-04-01 13:05 UTC, kotonefami requested changes
いろいろレビューしました。お手数ですがご確認お願いします。

2024-04-01 13:05 UTC, kotonefami commented on packages/os/index.ts
> +                                    const args = this.args
コロンはありに統一していただけるとありがたいです
同様の問題がいくつか存在します

2024-04-01 13:05 UTC, kotonefami commented on packages/os/index.ts
> +                                                const id = this.open(binaryFile,2)
openの第二引数はOpenFlag enumを使用して指定していただくようお願いします。

2024-04-01 13:05 UTC, kotonefami commented on packages/os/index.ts
> +                                        }else if(arg.startsWith("-")){
スペース開けのルールも統一していただきたいです。

```js
for(const arg of args){ // ...
```
となっていますが、
```js
for (const arg of args) { // ...
```
を使用しているのでそちらに変更をお願いします。

if文も同様の問題があります。

2024-04-01 13:05 UTC, kotonefami commented on packages/os/index.ts
> +                                                let LogicalOption = true;
おそらくローカル変数は先頭を小文字にするのがデファクトスタンダードなような気がします。

2024-04-01 13:15 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                        }else if(arg.startsWith("-")){
texttext:for (~) {}
の場合は
texttext: for (~) {}
に変えたほうが良いでしょうか...？

2024-04-01 13:35 UTC, kotonefami commented on packages/os/index.ts
> +                                        }else if(arg.startsWith("-")){
そうですね、コロンの後にもスペースあったほうがいいと思います。個人のコーディング規約ですが……。

2024-04-01 13:39 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                        }else if(arg.startsWith("-")){
おっけっす！

2024-04-01 13:42 UTC, kaonasi-biwa commented
レビューありがとうございます！

2024-04-01 15:00 UTC, kotonefami requested changes
（激重レビューを無断投下）

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                dataArray.push(await this.read(id));
そういえば思ったんですけど、これってdataArrayいります？
その都度（this.open, this.readの都度）出力すればいいような気もします

ただ、SIGINTを実装してないので中断ができませんが……できないけど本家は都度出力じゃないかなあという気がします

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                pwdArgs:for (const arg of args) {
catコマンドも同様ですが、`pwdArgs:`のあとはスペース一つ欲しいですね…お願いします…（強欲）

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                const args = command.slice(1)
マジで趣味なのでどうでもいいんですが、コピペビリティ（copy and paste + -bility）向上のために

```ts
const args = command.slice(1);
for (const arg or args) {
```
を
```ts
for (const arg or command.slice(1)) {
```
したほうがいいのではないでしょうか？すると変数の命名がわかりやすい（気がする）ので…
反論も全然大丈夫です。

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                    if(arg.startsWith("-")){
多分スペース漏れ

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                    } else{
どう見てもスペース漏れ

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                if (!isError){
スペースもｒ（ｒｙ

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                            for (const char of arg.slice(1)) {
ここfor文必要ですか？すぐ後に`break catArgs;`しちゃってるので不要なブロックな気がします

オプション実装のTODOならコメントでの明示をお願いします

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                const id = this.open(binaryFile, OpenFlag.READ);
ここでPATHとファイルの存在確認やってますが、まずPATHは本来の挙動では参照しませんので削除して大丈夫です。
またstatでのENOENT,EISDIR確認も不要です。fshでそうなっていたのはopenしないからであって、open時には自動的にENOENTが呼ばれるようになってます（Process.ts 183行目）。
結論としては、この処理は391行目からいきなり始めてもらって大丈夫です。

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                                    lib.io.write(`cat: ${fileName} : ディレクトリです\n`, 2);
`cat: ${fileName}: そのようなファイルやディレクトリはありません\n`
が正しいかと思います。2つ目のコロンの前ですね。

2024-04-01 15:00 UTC, kotonefami commented on packages/os/index.ts
> +                                    let notOptionIndex = 0
もしかして：コロン付け忘れ

2024-04-01 15:01 UTC, kotonefami commented on packages/os/index.ts
> +                                                const id = this.open(binaryFile, OpenFlag.READ);
補足: Linuxの慣例ではopenシステムコールで返されるファイルディスクリプタ番号はfd変数に入れます

2024-04-02 02:37 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                                dataArray.push(await this.read(id));
そっちのほうが楽でもあるのでそうしておきます！

2024-04-02 02:40 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                                    lib.io.write(`cat: ${fileName} : ディレクトリです\n`, 2);
OKです！

2024-04-02 02:43 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                                const args = command.slice(1)
あ～たしかにそっちのほうが読みやすいです！！

2024-04-02 02:52 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                                const id = this.open(binaryFile, OpenFlag.READ);
色々とありがとうございます！！

2024-04-02 02:54 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                            for (const char of arg.slice(1)) {
TODO書いときました！

2024-04-02 10:38 UTC, kotonefami approved these changes
引数パーサーがいい感じにできるまではこんな感じで行きましょう

2024-04-02 10:38 UTC, merged