Feat: #10 Added mkdir command
kotonone/kotonemu pull request #10
Opened 2024-05-17 12:10 UTC by kaonasi-biwa

2024-05-17 12:11 UTC, kaonasi-biwa commented
mkdirコマンドを追加しました
modeオプションも追加します

2024-05-17 12:54 UTC, kotonefami requested changes

2024-05-17 12:54 UTC, kotonefami commented on packages/os/index.ts
> +                                        makeDirectory(directoryPath);
`makeDirectory` をわざわざ関数にする必要ありますかね…？

2024-05-17 12:54 UTC, kotonefami commented on packages/os/index.ts
> +                                        const mode = 0o777
セミコロン抜け…

2024-05-17 12:55 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                        const mode = 0o777
ｳ

2024-05-17 12:56 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                        makeDirectory(directoryPath);
一応再起するためではありますけど、これよりわかりやすい方法があれば別に関数じゃなくてもいいかも...？

2024-05-17 12:58 UTC, kotonefami commented on packages/os/index.ts
> +                                        makeDirectory(directoryPath);
再帰してる部分ありますか？ぱっと見内容に見えるんですが…:thinking:

2024-05-17 13:05 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                        makeDirectory(directoryPath);
再帰っす

2024-05-17 13:25 UTC, kotonefami commented on packages/os/index.ts
> +                                        makeDirectory(directoryPath);
どこで再帰してますか？

2024-05-17 13:28 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                        makeDirectory(directoryPath);
...できてない()
1355行で再帰する予定でした

2024-05-18 16:09 UTC, kaonasi-biwa commented
chmod形式のPermissionを引数にしたらNumber型で返って来る関数・Number型のPermissionを引数にしたらls -l形式で変えてくる関数を作りました

前者についていくつか
- BaseDirectoryMode(ディレクトリのデフォルトのPermission), BaseFileMode(ファイルのデフォルトのPermission), umaskについては適切な場所に移動させたほうが良いと思います
- umaskで指定された権限のBitに関しては、`-rwxst`という引数でも削除されません。Linuxではこのことについてメッセージが出ますが、未実装です

2024-05-19 00:52 UTC, kotonefami approved these changes

2024-05-19 00:56 UTC, kotonefami commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
個人的になんだけど、こういうのは result とかの短い変数名に変えておいたほうがわかりやすい

気がする。デファクトスタンダードは知らん…

2024-05-19 00:56 UTC, kotonefami commented on packages/core/Utils.ts
> +        else baseMode = (BaseFileMode ^ umask);
ここだけ別関数に何とか分離できないかなあ（Twitterから転載）
getBasePermission(entry: IEntry) みたいな…

Baseという訳が正しいかどうかも一度検討したい

2024-05-19 00:56 UTC, kotonefami commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
うん？ここでもisDirectory使ってるのか
めんどくさ（独り言）

2024-05-19 00:57 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
そうなんっすよねぇ！！！！！

2024-05-19 00:57 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
こういう変数の命名本当に苦手なのでありがとうございます(((

2024-05-19 01:00 UTC, kotonefami commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
ところで関連して、 [string, string, string] である必要性ってある？ないならここで join したほうがいいんじゃないかなと思ったんですけど（必要性があるならこのままでいいです）

2024-05-19 01:00 UTC, kotonefami commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
うーん　ちょっとこれは私が的外れな話してたな、申し訳ない

Twitterでも聞いたけど、+Xって+xとどう違うの？
イーロンマスクかアルファベットかの違いとか？

2024-05-19 01:01 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
![image](https://github.com/kotonone/kotonemu/assets/85387717/411a392f-9d84-401c-9afa-eba4ae52801b)
umaskで将来的に使うことを考えました

2024-05-19 01:02 UTC, kotonefami commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
なるほど。それならこのままでもまあ許容範囲って感じがする

2024-05-19 01:03 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +        else baseMode = (BaseFileMode ^ umask);
baseは僕も違和感があるので変えたい()

2024-05-19 01:07 UTC, kotonefami commented on packages/core/Utils.ts
> +        else baseMode = (BaseFileMode ^ umask);
というか、これparsePermissionじゃなくてparseModeじゃないか…？

2024-05-19 01:07 UTC, kotonefami commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
ちょっと違うけど、さっきのparseModeと同じようにこっちはencodeMode…とかですかね？
encodeも違うかもしれない、いい案ありませんか？（parseはいろいろな意味があり対義語は文脈によって違うらしいので悩み中）

2024-05-19 01:09 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
①を0o0666,②を0o0667とします

u+x→①は0o0766、②は0o0767になる
u+X→
ディレクトリの場合: ①は0o0766、②は0o0767になる
ファイルの場合: ①は所持者・グループ・その他のユーザーどれもxに許可がないのでxは増やさず0o0666のまま、②はその他のユーザーにxの許可があるのでuにxを増やして0o767

2024-05-19 01:09 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +        else baseMode = (BaseFileMode ^ umask);
わかる(なんなら最初はそうしてたし)

2024-05-19 01:11 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
色々悩んだ末にわけわからなくなってdetailsに変えたって感じっすね...
そもそもこの動作をどう説明できるのか...()

2024-05-19 01:12 UTC, kotonefami commented on packages/core/Utils.ts
> +        else baseMode = (BaseFileMode ^ umask);
変数名initialMode, 関数名parseMode…がいいかな

2024-05-19 01:13 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +        else baseMode = (BaseFileMode ^ umask);
おっけっす！

2024-05-19 01:14 UTC, kotonefami commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
Linuxになんでそんなオプションがあんねん（引

マジか～、結構めんどくさいなそのオプション
どこかドキュメントありますか？一度読んでそもそも実装するかどうかの検討をしたいです。

2024-05-19 01:15 UTC, kotonefami commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
個人的には JSON.stringify っぽさはあるなと思いました
あとはやっぱりエンコード系、数値を人間が読みやすい文字列に直すわけですし…

Linuxのソースコードの同じことしてる部分を見つけられたらわかりやすいかな？探してみます

2024-05-19 01:15 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
https://www.ibm.com/docs/ja/aix/7.2?topic=c-chmod-command

2024-05-19 01:17 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
わかります！！
最初はstringifyにしようとしてました！！

ただ、検索してもJSON.stringify以外の使い方をあんまり見なかったので()

2024-05-19 01:18 UTC, kotonefami commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
https://ejje.weblio.jp/content/stringify

JSONでしか使われてない単語かもしれねぇ…

2024-05-19 01:19 UTC, kotonefami commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
いや～これ割とどこにでもある、実装しなきゃいけないな

2024-05-19 01:20 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +                    if (((umaskMode & 0o0111) & returnMode) || isDirectory) {
Oh(((

2024-05-19 01:21 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
まぁ語源がちゃんとしてるし使っても良さそうな気はしなくもない()

2024-05-19 01:22 UTC, kotonefami commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
うん、まあ、string に -ify をつけただけだけどな…（）

2024-05-19 01:22 UTC, kotonefami commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
まあ stringifyMode だとJavaScriptやってる人からするとわかりやすいから全然阿智

2024-05-19 01:43 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +export function detailsPermission(mode: number): [string, string, string] {
おっけっす！

2024-05-19 03:20 UTC, kaonasi-biwa commented
とりあえずmkdir -mに対応しました
同じノリでchmod,rmに関しては行けそうな気もするんですけど、PR分けたほうが良いっすかね...？

2024-05-19 03:23 UTC, kaonasi-biwa commented
mkdirに関してはSELinux以外対応しております

2024-05-19 05:07 UTC, kotonefami commented
> とりあえずmkdir -mに対応しました 同じノリでchmod,rmに関しては行けそうな気もするんですけど、PR分けたほうが良いっすかね...？

分けたほうが好ましいけど、 #11 を先にやりたいなって気持ちがある
そっちはどうですか

2024-05-19 06:23 UTC, kaonasi-biwa commented
あ～たしかに#11あればなかなか楽になりそう()

2024-05-19 07:38 UTC, kaonasi-biwa commented
これって僕も手伝ったほうが良いやつっすかね...？

2024-05-19 07:46 UTC, kotonefami commented
いや、どっちでもいいんですけどとにかく作業に区切りがついたら教えてください

2024-05-19 07:53 UTC, kaonasi-biwa commented
おっけっす！
まぁmkdirが完成してキリが良いので一旦ここで終わろうかなとは思っています

2024-05-19 08:39 UTC, kotonefami commented
じゃあ #11 の通り分離しても大丈夫そうですかね

2024-05-19 09:08 UTC, kaonasi-biwa commented
大丈夫だと思います！

2024-05-19 09:17 UTC, kotonefami commented
じゃ今日分離します
今日中に分離できないかもしれないけど

2024-05-19 09:19 UTC, kotonefami requested changes

2024-05-19 09:19 UTC, kotonefami commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
おっと、resultになってないぜ

2024-05-19 09:20 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
ふぇふぇふぇ

2024-05-19 09:20 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +    const returnMode: [string, string, string] = ["", "", ""];
ふぁっ！？

2024-05-19 09:23 UTC, kotonefami requested changes

2024-05-19 09:23 UTC, kotonefami commented on packages/core/Utils.ts
> +    const resultMode: [string, string, string] = ["", "", ""];
`resultMode` じゃなくて `result` …（小声）

2024-05-19 09:23 UTC, kotonefami commented on packages/core/Utils.ts
> +    const resultMode: [string, string, string] = ["", "", ""];
なんかごめん

2024-05-19 11:10 UTC, kaonasi-biwa commented on packages/core/Utils.ts
> +    const resultMode: [string, string, string] = ["", "", ""];
ふぁ！？(((

2024-05-19 13:29 UTC, kotonefami approved these changes

2024-05-19 13:29 UTC, merged