Add ls command
kotonone/kotonemu pull request #7
Opened 2024-04-13 11:22 UTC by kaonasi-biwa

lsコマンドを一旦追加しました
オプションが非常に多いのでゆっくり追加していきます

2024-04-13 11:33 UTC, kotonefami requested changes

2024-04-13 11:33 UTC, kotonefami commented on packages/os/index.ts
> +                                    let directries = options.arguments;
綴りが間違っています。正しくは `directories` です。

2024-04-13 11:33 UTC, kotonefami commented on packages/os/index.ts
> +                                    const  filesList = (dir: string) => {
`const  filesList` と2つスペースが開いています。
あと変数名ですが、直感で `fileList` です。

2024-04-13 11:33 UTC, kotonefami commented on packages/os/index.ts
> +                                    const  filesList = (dir: string) => {
あと関数名は `fileList` にしないほうがよいかと思います。`getFileList` とかですかね。
もしそうなるのであれば、L597も `filesListArr` じゃなくて `fileList` ですね。そもそも `filesListArr` は意味が重複している気もします。

2024-04-13 11:33 UTC, kotonefami commented
また、先ほどの私のコミットで stat の symlink 対応（lstat, fstat追加）もしましたのでご確認ください。

2024-04-13 11:41 UTC, kaonasi-biwa commented
ありがとうございます！

2024-04-13 11:41 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                    const  filesList = (dir: string) => {
おっしゃるとおりです(((

2024-04-13 11:44 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                    let directries = options.arguments;
違和感の塊でしか無いと思ったらそういうことか...(((

2024-04-13 14:20 UTC, kotonefami commented
手違いで Storage.ts を入れてしまったのですが、そちらのブランチでの削除をお願いできますか？

2024-04-13 14:22 UTC, kotonefami commented
> 手違いで Storage.ts を入れてしまったのですが、そちらのブランチでの削除をお願いできますか？

できればこのPRページに表示される私のコミット自体をなかったことにしてほしいのですが…（gitの操作的に難しい）

2024-04-13 14:24 UTC, kotonefami commented
こちらから削除できることに気づきましたので対応は不要です。ご迷惑をおかけし申し訳ないです。

2024-04-14 00:09 UTC, kaonasi-biwa commented
あっやらかした消してるほうが正しいのか

2024-04-14 00:22 UTC, kaonasi-biwa commented
戻せた

2024-04-14 03:58 UTC, kaonasi-biwa commented
`-U`,`-X`,`--all`,`--almost-all`,`--classify`,`--quote-name`,`-reverse`,`--sort=none`,`--sort=extension`,`--help`,`--version`に対応しました

2024-04-14 06:44 UTC, kotonefami requested changes

2024-04-14 06:44 UTC, kotonefami commented on packages/os/index.ts
> +                                                const directoryPath = directories[i]
コロンないよ

2024-04-14 06:44 UTC, kotonefami commented on packages/os/index.ts
> +                                            } catch (e){
`(e)` の後にはスペースを入れよう

2024-04-14 06:44 UTC, kotonefami commented on packages/os/index.ts
> +                                                        } else if (a === ".."){
`){` にはスペースを空けましょう

2024-04-14 06:44 UTC, kotonefami commented on packages/os/index.ts
> +                                        const getFileList = (dir: string) => {
前のレビューで気づかなくて申し訳ないのですが、`getFileList` 関数で `returnDataList` が返ってくるというのは命名としてやっぱりどうなんだろうと思ってきてしまいました。
例えば、`fileList` を `files` にして、 `returnDataList` を `fileList` にするほうがよかったりする（files = ファイル配列、fileList = （文字列としての）ファイルリスト　という意味を想定）のかなと思いました。

2024-04-14 06:44 UTC, kotonefami commented on packages/os/index.ts
> +                                                        if ((a.match( /\./g ) || [] ).length === 0) {
文法についての話: `|| [] )` の最後のスペースは消したほうが良いかと思われます。もしこうしたいのであれば、`if ( ( a.match(...) || [] ) )`のほうが適切かも。

演算子についての話: この場合においてはnull合体演算子を使用したほうがよろしいかと思われます。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing
`null_variable ?? string_variable` を計算すると `string_variable` が返ってきます。やってることは同じですが、まあ違いはMDNを見てください。

結論: そもそもこんな回りくどいことしなくても `a.includes(".")` でいいんじゃないでしょうか？何か理由があってのことですか？

2024-04-14 06:44 UTC, kotonefami commented on packages/os/index.ts
> +                                                    // TODO: executable-file
これって消し忘れでしょうか？L735にxが付いた時の処理は記載されています。

2024-04-14 08:00 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                                const directoryPath = directories[i]
あ～((((((

2024-04-14 08:01 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                                    // TODO: executable-file
消し忘れっす！

2024-04-14 08:04 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                                        if ((a.match( /\./g ) || [] ).length === 0) {
あった鹿にincludesでいい...

(一応このコードはピリオドの数を1,2とかで分けてたときの名残ですが...必要ないですねもう((()

2024-04-14 08:07 UTC, kaonasi-biwa commented on packages/os/index.ts
> +                                        const getFileList = (dir: string) => {
おっけっす！！

2024-04-14 09:25 UTC, kotonefami commented on packages/os/index.ts
> +                                                        if ((a.match( /\./g ) || [] ).length === 0) {
> 一応このコードはピリオドの数を1,2とかで分けてたときの名残ですが
なるほどですね
正規表現使うと少なからず負荷かかる（はず）ので削っていきましょう

2024-04-15 14:06 UTC, kotonefami commented
あれこれって作業終了してますか？してないなら正直にしてないですって言ってくれればいいです
ただunresolvedなので気になっただけです

2024-04-17 13:43 UTC, kaonasi-biwa commented
一応修正作業は終了しているはずです！

2024-04-17 13:43 UTC, kaonasi-biwa commented
オプション追加はもう少しやりたいので週末までお待ちを...

2024-04-17 13:49 UTC, kotonefami commented
おけです、mergeできるようになったら教えてください

2024-04-21 08:44 UTC, kaonasi-biwa commented
`-b(--escape,--quoting-style=escape)`,`-N(--literal,--quoting-style=literal)`,`-q(--hide-control-chars)`,`--show-control-chars`,`--quoting-style=shell`,`--quoting-style=shell-always`,`--quoting-style=shell-escape`,`--quoting-style=shell-escape-always`,`--quoting-style=c`,`--quoting-style=c-maybe`に対応しました
また、名前のみ`--quoting-style=locale`,`--quoting-style=clocale`,`-v(--sort=version)`,`-t(--sort=time)`,`-S(--sort=size)`を追加しました

2024-04-21 08:44 UTC, kaonasi-biwa commented
正直やることが多すぎるので、`-l`とそれに付随するコマンドを追加したら一旦lsから離脱しようと思います
その時にマージをお願いします

2024-04-28 02:12 UTC, kaonasi-biwa commented
`--file-type`,`-p`,`--indicator-style`を追加

2024-04-28 02:43 UTC, kaonasi-biwa commented
`-R`を追加

2024-04-28 02:57 UTC, kaonasi-biwa commented
今のうちに追加する予定がないオプションをまとめておきます
- `--author`: おそらく現時点で不可能
- `-h (--human-readable)`,`--si`,`-k`,`--block-size=SIZE`,`-S (--sort=size)`: ファイルサイズが関わるので一旦放置
- `-c`,`-u`,`--time=WORD`,`--time-style=STYLE`,`-t (--sort=time)`: ファイルの時刻周りが必要なので一旦放置
- `i`,`s`,`Z`: わけわからん
- `-C (format=vertical)`,`-x (format=across, format=horizontal)`: 実装方法がわからん
- `--tabsize=`,`--width=`: わからん
- `--quoting-style=locale`,`--quoting-style=clocale`: やりたいことがわからない
- `--color[=WHEN]`: 環境変数が必要・めんどい
- `-f`: `--color`が必要
- `-B (--ignore-backups)`,`--ignore=PATTERN`,`--hide=PATTERN`: わからんしめんどい
- `-H (--dereference-command-line)`,`--dereference-command-line-symlink-to-dir`,`-L (--dereference)`: 何がやりたいのかわからない

多分この中でも実装難易度に大幅な幅があると思うので良ければ()

2024-04-29 23:27 UTC, kaonasi-biwa commented
あと、出力先がターミナルかどうかでON/OFFが切り替わるものがあるので、何かしらの方法で判断できればいいなと思います

2024-05-04 13:58 UTC, kaonasi-biwa commented
メモ
実装が必要なオプション
`--format`,`-g`,`-G (--no-group)`,`-l`,`-n (--numeric-uid-gid)`,`-o`
`-g`と`-G`は同一扱いします

あと追加で
`-d (--directory)`,`-D (--dired)`,`--group-directories-first`
も現時点では実装しません

2024-05-04 14:13 UTC, kaonasi-biwa commented
`-C (--format=vertical)`はデフォルト値なので追加しておきます

2024-05-04 15:24 UTC, kaonasi-biwa commented
![image](https://github.com/kotonone/kotonemu/assets/85387717/2f62420d-e553-4d0f-8d84-ac7e3925c26e)
`-l`,`-g`,`-o`,`-G (--no-group)`,`-n (--numeric-uid-gid)`
を追加しました！
これからしばらく(少なくてもlsは)触る予定はないので、マージOKです！

2024-05-05 05:27 UTC, kotonefami commented
一応これでマージする予定ですが、少し聞きたいことが
- 追加予定オプションは--helpで見えないようになってますか？
- --colorについて、色をつけること自体では現時点でも可能ですが、どの環境変数が必要ですか？

2024-05-05 06:54 UTC, kaonasi-biwa commented
追加予定オプションについて:
--helpでも表示はしていません

--color:
LS_COLORSが必要です
https://qiita.com/aosho235/items/6e4737a1eca11c41da9b
あと、--color=autoを作るために、出力が端末かどうかを判断する方法がほしいかもっす...(最悪なくてもなんとかはなります)

2024-05-05 07:02 UTC, kaonasi-biwa commented
(まぁ...正直--colorはめんどいっちゃめんどい...((()

2024-05-05 07:06 UTC, kotonefami commented
端末ってどういう感じでしょうか？ttyかptyかで判別できないでしょうか？

2024-05-05 10:36 UTC, kaonasi-biwa commented
どうやればいいんだろう…(おい)
やりたいことは、端末ならtrue、(今はないですが)ファイルへのパイプならfalse…みたいな感じです

2024-05-06 00:16 UTC, kotonefami commented
めちゃくちゃこのPRにToDo的なものつけたいけど、やりかたわからないのでとりあえずmerge

2024-05-06 00:16 UTC, merged